# Generated by Django 5.2.12 on 2026-04-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('chat_log_id', models.BigAutoField(editable=False, help_text='不要亂弄喔', primary_key=True, serialize=False, verbose_name='訊息 ID')),
                ('message_content', models.TextField(verbose_name='訊息內容')),
                ('sender', models.CharField(choices=[('user', '用戶'), ('assistant', '機器人')], default='user', max_length=10, verbose_name='發送者角色')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='用來排聊天順序', verbose_name='傳送時間')),
                ('sentiment_score', models.FloatField(blank=True, help_text='用來做週總結的，如果是 LLM 的回覆就設成 null', null=True, verbose_name='此訊息的情緒分數')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='表示這則訊息有沒有被刪除', verbose_name='是否啟用這則訊息')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最後更新時間', verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '聊天訊息',
                'verbose_name_plural': '聊天訊息清單',
                'ordering': ['timestamp', '-updated_at', '-chat_log_id'],
            },
        ),
        migrations.CreateModel(
            name='AIModelRegistry',
            fields=[
                ('model_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='模型 ID')),
                ('model_type', models.CharField(choices=[('llm', '對話模型 (LLM)'), ('nlp', '情緒分析模型 (NLP)')], max_length=10, verbose_name='模型用途')),
                ('model_name', models.CharField(help_text='請填完整模型名稱 (名字＋版本，例如 TAIDE-8B)', max_length=200, verbose_name='模型名稱')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='只有一個模型會處於 True 的狀態', verbose_name='是否為當前使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='模型上線時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': 'AI 模型',
                'verbose_name_plural': '模型清單',
                'ordering': ['-is_active', '-updated_at', 'model_type'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.BigAutoField(editable=False, help_text='不要給我亂動', primary_key=True, serialize=False, verbose_name='Session ID')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最後一輪對話完成時間')),
                ('session_summary', models.TextField(blank=True, help_text='這個之後會用 LLM 自動摘要，不用管', null=True, verbose_name='當前對話階段摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='階段創建時間(對話開始時間)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='讓用戶選擇要不要刪掉聊天紀錄', verbose_name='是否啟用這段對話紀錄(有沒有被刪除)')),
            ],
            options={
                'verbose_name': '聊天階段',
                'verbose_name_plural': '聊天階段清單',
                'ordering': ['-last_activity', '-user', '-session_id'],
            },
        ),
        migrations.CreateModel(
            name='SOSLog',
            fields=[
                ('sos_id', models.BigAutoField(editable=False, help_text='動了會世界末日', primary_key=True, serialize=False, verbose_name='預警 ID')),
                ('triggering_keyword', models.CharField(help_text='這個會用 LLM 辨識再用程式處理，不要亂動', max_length=200, verbose_name='觸發預警的詞或句子')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='觸發預警時間')),
                ('action_taken', models.CharField(choices=[('crisis_intv', '危機截斷 (暫停功能，導向外部專線)'), ('chat_invite', '彈窗導引 (邀請用戶進入聊天室)'), ('prompt_switch', '模式切換 (將涵涵切換為「深度陪伴」指令)'), ('push_article', '文章推薦 (推送情緒穩定或心理衛教文章)'), ('push_media', '影音推薦 (推送放鬆音樂或 Podcast)'), ('push_scale', '量表引導 (建議進行心情溫度計 BSRS-5 測驗)'), ('monitor', '僅標記監測 (不干擾用戶，但列入週報重點回顧)')], default='monitor', help_text='一開始會用模型快速判定，必要時管理員可調整', max_length=50, verbose_name='針對預警採取的動作標籤')),
            ],
            options={
                'verbose_name': '安全預警',
                'verbose_name_plural': '預警清單',
                'ordering': ['-timestamp', '-sos_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('prompt_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='System Prompt ID')),
                ('prompt_name', models.CharField(help_text='例如：溫暖陪伴版 v1.1', max_length=100, verbose_name='版本名稱')),
                ('content', models.TextField(verbose_name='指令內容')),
                ('is_active', models.BooleanField(default=False, help_text='系統會抓取此欄位為 True 的指令來與用戶對話', verbose_name='是否為當前使用中')),
                ('version_note', models.CharField(blank=True, max_length=200, verbose_name='更新說明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Prompt',
                'verbose_name_plural': 'System Prompt 清單',
                'ordering': ['-is_active', '-created_at', '-prompt_id'],
            },
        ),
    ]
