# Generated by Django 5.2.12 on 2026-04-15 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='關聯用戶'),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='llm_model',
            field=models.ForeignKey(blank=True, help_text='這個不管用戶輸入或 LLM 回答都會記錄', limit_choices_to={'model_type': 'llm'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='llm_chat_logs', to='ai_chatbot.aimodelregistry', verbose_name='對話當下使用的模型'),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='nlp_model',
            field=models.ForeignKey(blank=True, help_text='這個只計算用戶數入的情緒分數', limit_choices_to={'model_type': 'nlp'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='nlp_chat_logs', to='ai_chatbot.aimodelregistry', verbose_name='用來計算情緒分數的的 NLP 模型'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='關聯用戶'),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_chatbot.chatsession', verbose_name='關聯對話階段'),
        ),
        migrations.AddField(
            model_name='soslog',
            name='chat_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='triggered_sos', to='ai_chatbot.aichatlog', verbose_name='觸發預警的對話'),
        ),
        migrations.AddField(
            model_name='soslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_logs', to=settings.AUTH_USER_MODEL, verbose_name='關聯用戶'),
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='system_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='logs', to='ai_chatbot.systemprompt', verbose_name='關聯指令版本'),
        ),
    ]
