# Generated by Django 5.2.12 on 2026-04-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemprompt',
            options={'ordering': ['-is_active', '-updated_at', '-prompt_id'], 'verbose_name': 'System Prompt', 'verbose_name_plural': 'System Prompt 清單'},
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
