# Generated by Django 5.2.12 on 2026-04-15 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KudosNote',
            fields=[
                ('note_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='誇誇 ID')),
                ('praise_content', models.TextField(help_text='對自己的讚美 or 成就感紀錄', verbose_name='誇誇 or 成就內容')),
                ('mood_score', models.SmallIntegerField(default=5, help_text='1(極度低落) ~ 10(極度正向)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='心情分數')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='誇誇創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '誇誇',
                'verbose_name_plural': '誇誇清單',
                'ordering': ['-updated_at', '-created_at', '-note_id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('review_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='報告 ID')),
                ('review_start_date', models.DateField(help_text='週回顧的第一天', verbose_name='回顧起始日期')),
                ('review_end_date', models.DateField(help_text='週回顧的第七天', verbose_name='回顧結束日期')),
                ('summary_visualization_data', models.JSONField(default=list, help_text='儲存這週的所有資料，用 JSON 儲存', verbose_name='統計資料（json）')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='可以拿來讓用戶選擇是否要顯示，或是管理員軟刪除', verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='報告創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
            ],
            options={
                'verbose_name': '週回顧',
                'verbose_name_plural': '週回顧清單',
                'ordering': ['-review_end_date', '-created_at', '-updated_at', '-review_id', '-user_id'],
            },
        ),
    ]
