# Generated by Django 5.2.12 on 2026-04-15 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_praise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kudosnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_notes', to=settings.AUTH_USER_MODEL, verbose_name='關聯用戶'),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to=settings.AUTH_USER_MODEL, verbose_name='關聯用戶'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreview',
            unique_together={('user', 'review_end_date')},
        ),
    ]
