# Generated by Django 5.2.12 on 2026-04-15 07:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('tag_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='標籤 ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
                ('category', models.CharField(choices=[('self', '自我描述'), ('topic', '心理主題')], max_length=20, verbose_name='標籤分類')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤清單',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='不准亂動，會用亂碼產生', primary_key=True, serialize=False, verbose_name='用戶 ID')),
                ('email', models.EmailField(help_text='請輸入電子郵件信箱(ex: 123456789@gmail.com)', max_length=500, unique=True, verbose_name='用戶 email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用戶',
                'verbose_name_plural': '用戶清單',
                'ordering': ['-date_joined', '-user_id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('setting_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='不准亂動，會用亂碼產生', primary_key=True, serialize=False, verbose_name='安全設定 ID')),
                ('is_anonymized', models.BooleanField(db_index=True, default=True, help_text='讓用戶選擇是否要匿名發貼文', verbose_name='是否啟用匿名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='安全設定創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to=settings.AUTH_USER_MODEL, verbose_name='關聯用戶')),
            ],
            options={
                'verbose_name': '安全設定',
                'verbose_name_plural': '安全設定清單',
                'ordering': ['-updated_at', '-created_at', '-setting_id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='不准亂動，會用亂碼產生', primary_key=True, serialize=False, verbose_name='Profile ID')),
                ('nickname', models.CharField(help_text='這就是讓用戶輸入他想要在網站上顯示的暱稱', max_length=100, verbose_name='用戶暱稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Profile 創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('interested_topics', models.ManyToManyField(blank=True, limit_choices_to={'category': 'topic'}, related_name='profiles_topic_tags', to='user_info.topictag', verbose_name='有興趣的主題')),
                ('self_description_tags', models.ManyToManyField(blank=True, limit_choices_to={'category': 'self'}, related_name='profiles_self_tags', to='user_info.topictag', verbose_name='自我描述標籤')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='關聯用戶')),
            ],
            options={
                'verbose_name': '用戶資訊',
                'verbose_name_plural': '用戶資訊清單',
                'ordering': ['-updated_at', 'nickname', '-created_at', '-profile_id'],
            },
        ),
    ]
